Add v3 to auth_uri: (#3311)
auth_uri needs to be the fully versioned url otherwise Heat
will throw this error:

heatclient.exc.HTTPInternalServerError: ERROR: Remote error: AuthorizationFailure Authorization failed: The resource could not be found. (HTTP 404) (HTTP 404)